# Generated by Django 2.1.7 on 2019-03-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20190322_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(related_name='post_category', to='topic.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topic.Category'),
        ),
    ]
