# Generated by Django 2.1.7 on 2019-03-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_auto_20190322_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
