# Generated by Django 2.1.7 on 2019-03-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0015_auto_20190323_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
