# Generated by Django 2.1.7 on 2019-03-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0018_auto_20190323_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='topic.Post'),
        ),
    ]
