# Generated by Django 2.1.7 on 2019-03-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0019_auto_20190323_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='post_id',
            new_name='post',
        ),
    ]
