# Generated by Django 2.1.7 on 2019-03-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0025_auto_20190324_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
